apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jubileu-v1
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: jubileu
        version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "32111"
    spec:
      containers:
      - name: jubileu
        image: andersonrln/jubileu-canary-project:1.0.0
        env:
        - name: VERSION
          value: "1.0.0"
        ports:
        - containerPort: 80
        - containerPort: 32111
